### PR TITLE
Allow drain retries even with timeout failures.

### PR DESCRIPTION
**Pull request by shreyas-badiger**
Fixes https://github.com/keikoproj/lifecycle-manager/issues/90
- [x] Functional testing
- [x] Unit tests

### CODE REVIEW

**Comment by garomonegro** [comment]
Just a thought, doesn't need to be addressed in this PR: Any reason why we are still using vendor? Do we need to keep using it?

**Comment by shreyas-badiger** [comment]
> Just a thought, doesn't need to be addressed in this PR: Any reason why we are still using vendor? Do we need to keep using it?

@garomonegro  Good point. Even I wasn't sure why we need the vendors. However, they all got updated when I ran `go mod tidy` and `go get <missing_modules>`. Maybe should create another ticket to cleanup the vendors?

**Comment by kevdowney** [comment]
We can probably remove the entire `/vendor` dir here.

**Comment by kevdowney** [comment]
@shreyas-badiger Does this change simply add more retry and not change it's behavior in any other ways?

**Comment by shreyas-badiger** [comment]
> @shreyas-badiger Does this change simply add more retry and not change it's behavior in any other ways?

That's right. It allows drain retries even when there is a timeout error and also makes drain retry attempts configurable.

**Pull request closed without merging**
